In [2]:
import openpyxl
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import ElasticNet
from sklearn.tree import DecisionTreeRegressor
from sklearn import metrics
from sklearn.ensemble import RandomForestRegressor

from sklearn.feature_selection import RFE
from sklearn.feature_selection import RFECV
from sklearn.model_selection import StratifiedKFold

from matplotlib import pyplot as plt
import datetime
import math
import pandas as pd
from scipy import stats
import seaborn as sn

from IPython.core.display import display, HTML
display(HTML("<style>.container { width:98% !important; }</style>"))

In [4]:
egg_1_dataframe_1 = pd.read_csv('RAW_DATA/Egg#1/2020-05-16 Download_egg0080446e6e980130.csv')
egg_1_dataframe_2 = pd.read_csv('RAW_DATA/Egg#1/2020-05-25 Download_egg0080446e6e980130.csv')
egg_1_dataframe_3 = pd.read_csv('RAW_DATA/Egg#1/2020-06-02 Download_egg0080446e6e980130.csv')
# Remove the Latitude, Longitude, and Altitude 
egg_1_dataframe_1 = egg_1_dataframe_1.drop(columns=['Latitude[deg]', 'Longitude[deg]', 'Altitude[m]'])
egg_1_dataframe_2 = egg_1_dataframe_2.drop(columns=['Latitude[deg]', 'Longitude[deg]', 'Altitude[m]'])
egg_1_dataframe_3 = egg_1_dataframe_3.drop(columns=['Latitude[deg]', 'Longitude[deg]', 'Altitude[m]'])
# Convert the Timestamp column to an index and resample to 60 min averages
egg_1_dataframe_1['Timestamp'] = pd.to_datetime(egg_1_dataframe_1['Timestamp'])
egg_1_dataframe_2['Timestamp'] = pd.to_datetime(egg_1_dataframe_2['Timestamp'])
egg_1_dataframe_3['Timestamp'] = pd.to_datetime(egg_1_dataframe_3['Timestamp'])
# Merge all the files into 1 dataframe
egg_1_dataframe = pd.concat((egg_1_dataframe_1, egg_1_dataframe_2, egg_1_dataframe_3))
egg_1_dataframe['Timestamp'] = pd.to_datetime(egg_1_dataframe['Timestamp'])
egg_1_dataframe = egg_1_dataframe.resample('60min', on='Timestamp').mean()
egg_1_dataframe.to_pickle('RAW_DATA_HOURLY/Egg#1_06Jun2020_hourly.pkl')

egg_2_dataframe_1 = pd.read_csv('RAW_DATA/Egg#2/2020-05-16 Download_egg0080446fa82b0130.csv')
egg_2_dataframe_2 = pd.read_csv('RAW_DATA/Egg#2/2020-05-25 Download_egg0080446fa82b0130.csv')
egg_2_dataframe_3 = pd.read_csv('RAW_DATA/Egg#2/2020-06-02 Download_egg0080446fa82b0130.csv')
# Remove the Latitude, Longitude, and Altitude 
egg_2_dataframe_1 = egg_2_dataframe_1.drop(columns=['Latitude[deg]', 'Longitude[deg]', 'Altitude[m]'])
egg_2_dataframe_2 = egg_2_dataframe_2.drop(columns=['Latitude[deg]', 'Longitude[deg]', 'Altitude[m]'])
egg_2_dataframe_3 = egg_2_dataframe_3.drop(columns=['Latitude[deg]', 'Longitude[deg]', 'Altitude[m]'])
# Convert the Timestamp column to an index and resample to 60 min averages
egg_2_dataframe_1['Timestamp'] = pd.to_datetime(egg_2_dataframe_1['Timestamp'])
egg_2_dataframe_2['Timestamp'] = pd.to_datetime(egg_2_dataframe_2['Timestamp'])
egg_2_dataframe_3['Timestamp'] = pd.to_datetime(egg_2_dataframe_3['Timestamp'])
# Merge all the files into 1 dataframe
egg_2_dataframe = pd.concat((egg_2_dataframe_1, egg_2_dataframe_2, egg_2_dataframe_3))
egg_2_dataframe['Timestamp'] = pd.to_datetime(egg_2_dataframe['Timestamp'])
egg_2_dataframe = egg_2_dataframe.resample('60min', on='Timestamp').mean()
egg_2_dataframe.to_pickle('RAW_DATA_HOURLY/Egg#2_06Jun2020_hourly.pkl')

egg_4_dataframe_1 = pd.read_csv('RAW_DATA/Egg#4/2020-05-16 Download_egg00804426a6980132.csv')
egg_4_dataframe_2 = pd.read_csv('RAW_DATA/Egg#4/2020-05-25 Download_egg00804426a6980132.csv')
egg_4_dataframe_3 = pd.read_csv('RAW_DATA/Egg#4/2020-06-02 Download_egg00804426a6980132.csv')
# Remove the Latitude, Longitude, and Altitude 
egg_4_dataframe_1 = egg_4_dataframe_1.drop(columns=['Latitude[deg]', 'Longitude[deg]', 'Altitude[m]'])
egg_4_dataframe_2 = egg_4_dataframe_2.drop(columns=['Latitude[deg]', 'Longitude[deg]', 'Altitude[m]'])
egg_4_dataframe_3 = egg_4_dataframe_3.drop(columns=['Latitude[deg]', 'Longitude[deg]', 'Altitude[m]'])
# Convert the Timestamp column to an index and resample to 60 min averages
egg_4_dataframe_1['Timestamp'] = pd.to_datetime(egg_4_dataframe_1['Timestamp'])
egg_4_dataframe_2['Timestamp'] = pd.to_datetime(egg_4_dataframe_2['Timestamp'])
egg_4_dataframe_3['Timestamp'] = pd.to_datetime(egg_4_dataframe_3['Timestamp'])
# Merge all the files into 1 dataframe
egg_4_dataframe = pd.concat((egg_4_dataframe_1, egg_4_dataframe_2, egg_4_dataframe_3))
egg_4_dataframe['Timestamp'] = pd.to_datetime(egg_4_dataframe['Timestamp'])
egg_4_dataframe = egg_4_dataframe.resample('60min', on='Timestamp').mean()
egg_4_dataframe.to_pickle('RAW_DATA_HOURLY/Egg#4_06Jun2020_hourly.pkl')

In [5]:
egg_1_dataframe

,Temperature[degC],Humidity[percent],PM1.0[ug/m^3],PM2.5[ug/m^3],PM10.0[ug/m^3],O3[ppb],O3[V],NO2[ppb],NO2[V],Pressure[Pa]
Timestamp,,,,,,,,,,
2020-05-06 13:00:00,20.520000,20.116667,3.166667,3.666667,4.000000,142.300000,1.421641,1935.236667,1.410120,99261.900000
2020-05-06 14:00:00,17.968333,24.757292,13.868750,15.925000,16.810417,63.958958,1.423080,263.038333,1.422146,99264.718750
2020-05-06 15:00:00,22.348833,19.432667,1.673333,2.333333,2.475000,60.012667,1.423583,95.994500,1.423568,99188.643333
2020-05-06 16:00:00,22.438667,18.594000,1.186667,1.920000,2.090000,61.118000,1.423567,56.341500,1.423861,99138.068333
2020-05-06 17:00:00,22.471500,18.093833,1.471667,2.248333,2.441667,62.872167,1.423533,49.240500,1.423915,99108.190000
...,...,...,...,...,...,...,...,...,...,...
2020-06-02 09:00:00,17.769333,56.769000,4.976667,6.965000,7.448333,42.764333,1.423516,45.984500,1.423708,99397.595000
2020-06-02 10:00:00,18.665833,55.354500,12.606667,18.260000,20.106667,44.410500,1.423566,60.210000,1.423650,99301.313333
2020-06-02 11:00:00,22.390833,46.859167,4.021667,5.456667,5.803333,43.110333,1.423955,70.113000,1.423761,99201.498333
2020-06-02 12:00:00,27.310333,38.680833,4.776667,6.323333,6.700000,45.406833,1.424451,83.049500,1.423917,99088.415000
2020-06-02 13:00:00,28.563220,35.733220,4.679661,6.245763,6.613559,67.812881,1.424123,155.186271,1.423448,98953.352542

In [18]:
airpointer = pd.read_csv('RAW_DATA_HOURLY/20200612_181135_2019_00697_HC_697_9236.csv')
airpointer = airpointer.rename(columns={'Time': 'Timestamp'})
airpointer.set_index('Timestamp', inplace=True)
airpointer.to_pickle('AIRPOINTER_DATASET.pkl')
airpointer

,NO,NO2,NOx,O3,PM10_conc,PM10-2.5_conc,PM2.5_conc,Air_Temperature
Timestamp,,,,,,,,
2020-05-06 00:00:00,1.096,8.023,9.571,25.016,11.329,7.410,3.922,4.317
2020-05-06 01:00:00,0.181,8.131,8.309,24.151,10.687,6.981,3.711,3.914
2020-05-06 02:00:00,0.279,9.085,9.364,21.797,10.793,6.913,3.875,3.570
2020-05-06 03:00:00,0.664,10.384,11.048,20.057,10.924,6.616,4.308,3.374
2020-05-06 04:00:00,1.368,9.892,11.259,20.484,11.827,7.190,4.638,3.379
...,...,...,...,...,...,...,...,...
2020-06-12 14:00:00,0.853,1.669,2.444,34.309,8.254,7.223,1.029,18.268
2020-06-12 15:00:00,0.949,2.071,3.020,34.092,6.185,4.869,1.315,18.792
2020-06-12 16:00:00,0.764,2.105,2.869,34.413,9.185,7.106,2.079,18.185
2020-06-12 17:00:00,0.584,1.671,2.255,36.632,13.137,10.437,2.700,16.967
2020-06-12 18:00:00,0.676,1.987,2.663,36.596,8.539,6.292,2.250,16.041